### ISSUE TITLE
ng-pdf-viewer showing black screen 

### ISSUE THREAD

**Issue by goyalsunil452** [VadimDez/ng2-pdf-viewer#1090]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
When I am using this url (https://dev.production.nslhub.com/dsd-orch/dsd-files-store/content/grafdev/other/tempce07eb00-22d8-417e-ad9d-0acad609bc06.pdf )
it is showing black screen. But if I use browser then I am able to see this pdf.
![image](https://github.com/VadimDez/ng2-pdf-viewer/assets/79658759/add782fc-56eb-42e4-a859-f9af2cde9b69)

**Comment by ftaffelt** [comment]
The problem is not related to ng2-pdf-viewer. It's more related to the underlying pdfjs library which is used by ng2-pdf-viewer. Opening the url directly in:
- chrome works because it's an annother pdflibray
- firefox fails and also shows a black screen

You should report this as a bug to pdfjs project.

**Comment by goyalsunil452** [comment]
Thanks @ftaffelt

**Comment by AndrewWeiser-RTWSA** [comment]
This kind of defeats a big purpose of this plugin. Displaying a PDF in a rectangular area used to work as of ng_pdf-viewer 6.x, but broke possibly since version 7. It's disappointing that this is just finger-pointed at a dependency.
