### ISSUE TITLE
Canvas deleted from page division when scroll

### ISSUE THREAD

**Issue by dixit-atharva** [VadimDez/ng2-pdf-viewer#1133]
When PDF has more then 10 pages and when i scroll down to page number 11 it blacks the first page canvas due to it lost the dropped item on canvas.

**Comment by VadimDez** [comment]
I'm not sure I can reproduce your issue. Are you able to reproduce it here - https://vadimdez.github.io/ng2-pdf-viewer/ ?

**Comment by dixit-atharva** [comment]
![image](https://github.com/user-attachments/assets/61a285e3-e1ee-4fff-9f89-5f42f8736a7a)
@VadimDez  Please find uploaded image, try to upload PDF have more then 10 pages and scroll down slowly you will able to see first page canvas element is delete from it.

**Comment by VadimDez** [comment]
if you scroll back to the first page, can you see it?

**Comment by dixit-atharva** [comment]
Yes when i get back to page 1 i can see it again, but issue is right away like i have placed division over pdf canvas that also delete from it.

**Comment by ftaffelt** [comment]
Yes, this is the expected behaviour from PDFJS and so also from ng2-pdf-viewer. PDFJS renders only the visible pages, which are in the viewport plus some pages before and after this pages in the viewport. Pages which are not more in the visible range are "offloaded", meaning their canvas are removed from the DOM, to reduce memory footprint. If this page becomes visible again, the canvas will be readded to the DOM. Maybe your expaction from the option "Show all pages" is leading in the wrong way?

**Comment by dixit-atharva** [comment]
Yeah i think so is there any way i can stop the offload or it or can set the visible pages range  ?

**Comment by ftaffelt** [comment]
Not that i know, as this is deeply baked into the PDJS.

**Comment by shamoon** [comment]
Should be closed as above
