### ISSUE TITLE
Update pdfjs-dist to v4.6.82

### ISSUE THREAD

**Issue by SaschaSchwarz** [VadimDez/ng2-pdf-viewer#1139]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```
The dependency on TS 5.6 was introduced in [pdfjs-dist v4.7.76](https://github.com/mozilla/pdf.js/releases/tag/v4.7.76).  Which led to the changes in #1138.

However, the most recent version `<4.7.76` is [v4.6.82](https://github.com/mozilla/pdf.js/releases/tag/v4.6.82).

**Comment by studioromeo** [comment]
Good call. I imagine it shouldn't be locked to a specific version rather track semver otherwise we will continuously miss out on fixes from pdfjs upstream. `~` would be the appropriate choice here https://github.com/npm/node-semver#tilde-ranges-123-12-1 which allows patch level changes but denies minor.

**Comment by shamoon** [comment]
I don’t believe they backfill releases so I don’t think there will be any minor versions < 4.7 so no point in ~ but you’re right I could’ve taken the opportunity to update to 4.6. I was more focused on un-breaking things
