### ISSUE TITLE
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType

### ISSUE THREAD

**Issue by penniath** [VadimDez/ng2-pdf-viewer#259]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Hello,

After installing the current latest version '3.0.8', and including the PdfViewerModule module to the imports list of one of my lazy loaded modules, the following log is displayed to the console. This message is logged even before I try to use the viewer in any of my components.

> The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.

Regards,

Fernando

**Comment by rsaulo** [comment]
+1 for this problem 

Any solution?

**Comment by svallepalli** [comment]
same problem.

**Comment by ShadowQueen** [comment]
+1

**Comment by Ristaaf** [comment]
The warning comes from the dependency pdfjs-dist, and it is tracked here: https://github.com/mozilla/pdf.js/issues/6306
Following links etc on that one and it seems like it is fixed (or rather went away because of a rewrite) in version 1.10 which is just a pre-release, so I guess that when that is released and ng2-pdf-viewer updates its dependency the warning will be gone
