### ISSUE TITLE
Single page pdf are never displayed

### ISSUE THREAD

**Issue by UlricW** [VadimDez/ng2-pdf-viewer#320]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ x] Bug report -> please search issues before submitting
```
Hello,
I've a problem to display a single page pdf. All works fine with a multiple pages pdf but for single page pdf, the event (page-rendered) is never triggered. Moreover the (onError) event is not triggered either.
This strange behaviour appears for 10 days, before that the render worked. I tried to update ng2-pdf-viewer but behaviour is the same
Anyone can help me ?

**Comment by Philam18** [comment]
Multi-page PDF's don't seem to be working for me either - both single and multi-page show white-boxes with infinite loads. 
Neither trigger `onProgress()` or `onError()` either.

**Comment by mfrro** [comment]
I'm experiencing the same issue (single page pdf not rendering / multi-page pdf rendering). It turns out that in my case this is related to the position of the <pdf-viewer> element relative to the top of the page. If the element is more than 1132px from the top, the pdf won't render. 
@UlricW could you confirm that you're experiencing the same issue? Here's a sample to reproduce:
```
<div style="height:1133px;"></div>
<pdf-viewer [src]="previewDocumentSrc"></pdf-viewer>
```

**Comment by UlricW** [comment]
Yes you’re right. 
I didn’t have time to post the  solution before but this is due to the size. We have a dynamic component with multiple lines and if the component’s heigt is too big thumbnails are never displayed above the component. 
Thanks for your experience sharing
