### ISSUE TITLE
How to display PDF in Mobile View in Angular 5 or 6 or 7?

### ISSUE THREAD

**Issue by pankajgoelknab** [VadimDez/ng2-pdf-viewer#438]
I want to Display Agreement PDF version in mobile view in angular 5,6,7 . Its should not open in new tab..

**Comment by bh-adrienne** [comment]
If you just don't want to open a link in a new tab, then do the opposite of this question: 
https://stackoverflow.com/questions/17711146/how-to-open-link-in-new-tab-on-html#17711167

If you're asking about how to force a link from a website to open a particular phone application, 
this is **not possible** with this library, or any Javascript web browser library, and the reason is obvious: a website can't know ahead of time what PDF mobile viewer a phone might have. This is configured by the user's phone- on my phone I can have multiple apps for looking at a PDF and my phone settings choose which one I use to open PDFs, not the website.  See this stack overflow post for a more detailed explanation: 
https://android.stackexchange.com/questions/37549/force-links-to-open-in-the-app-not-the-default-browser
