### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by javid-abd** [VadimDez/ng2-pdf-viewer#444]
```
- [X ] Bug report -> please search issues before submitting
```

Access to fetch at 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' from origin 'https://dashboard.finna.ai' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

(this is just a test remote URL)

I can't use any remote URL for pdf rendering. All of these point out this CORS problem. It used to work properly but it seems something as changed.

@angular/core 7.2.2
@angular/cli 7.2.3

**Comment by ColinT** [comment]
It is unlikely that this behavior is a reversion since it is not supported by the underlying pdfjs viewer.
Please refer to the following documentation:
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr
https://github.com/mozilla/pdf.js/issues/1000#issuecomment-133756244

For development purposes you can use the cors-anywhere public demo server:
`[src]="'https://cors-anywhere.herokuapp.com/https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf'"`
[stackblitz demo](https://stackblitz.com/edit/angular-tupyq7)
