### ISSUE TITLE
 peer dependency for pdfjs-dist

### ISSUE THREAD

**Issue by maxisam** [VadimDez/ng2-pdf-viewer#461]
https://github.com/VadimDez/ng2-pdf-viewer/blob/528043dc17b50ecbb8f818ab780fc477629cc0cf/package.json#L37

Since  pdfjs-dist is in the dependency already. Do we still need it in peerDependency?

**Comment by dhyanaswain** [comment]
it's better to add the PDF.js package to your NodeModule.
As every pdf viewer use pdf.js in the backend to load any pdf files.

**Comment by maxisam** [comment]
Well, but I don't need PDF.js, it kinda pollutes my package.json if every package does this.

**Comment by dhyanaswain** [comment]
Yes, some of the packages generates this "peerDependencies"

**Comment by JoostK** [comment]
I would like to raise this issue as well. We were seeing an issue in https://github.com/mgechev/ngcc-validation/pull/220 in the situation where there was an additional package with a peer dependency on `pdfjs-dist`, so `pdfjs-dist` was present as dependency of the project itself, to satisfy said dependency. This caused an issue with duplicate installations of `pdfjs-dist`, probably because of the direct dependency on `pdfjs-dist` from `ng2-pdf-viewer`.

Note that it is strange to list a package both as dependency *and* as peer dependency, as the former will cause the requested version to be installed, whereas the latter is just a signal to library consumers to let people know they need to include the peer dependency as a dependency of their own.

For libraries, it is typically considered best practice to mark dependencies as peer dependency, as it avoids ending up with multiple versions of the some package "A" if there's other packages that depend on "A". Note, however, that removing the direct dependency would be a breaking change, as library consumers would suddenly be responsible for listing the dependency in their own `package.json`.

**Comment by maxisam** [comment]
this causes an issue in Angular9 now

Because ngcc can't figure out which package it should use. We should just keep one. 

```
ERROR in ./node_modules/ng2-pdf-viewer/__ivy_ngcc__/node_modules/pdfjs-dist/build/pdf.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\xxx\WorkProject-git\xxxx\xxxx\ClientApp\node_modules\ng2-pdf-viewer\__ivy_ngcc__\node_modules\pdfjs-dist\build'
```

**Comment by VadimDez** [comment]
https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/6.2.0
