### ISSUE TITLE
Ionic 4 / Angular 7 - Can't bind to 'src' since it isn't a known property of 'pdf-viewer'

### ISSUE THREAD

**Issue by johncressman** [VadimDez/ng2-pdf-viewer#486]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I installed and imported it into my app.module.ts file
`import { PdfViewerModule } from 'ng2-pdf-viewer';

@NgModule({
  declarations: [AppComponent, SearchPipe, SortPipe],
  entryComponents: [],
  imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule,  HttpClientModule, PdfViewerModule, NgbModule.forRoot()],
  providers: [
    StatusBar,
    SplashScreen,
    GetMenuService,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}`

I put the code in my html file and it's not recognizing it.
`<ion-content>
  <h2>PDF Viewer</h2>

  <div class="pdf-container">
    <pdf-viewer [src]="src"
                [original-size]="false"
    ></pdf-viewer>
  </div>
</ion-content>`

In the IDE (ItelliJ), it's telling me "Component or directive matching pdf-viewer element is out of the current Angular module's scope"

**Comment by VadimDez** [comment]
Looks like duplicate of #289

**Comment by vespina** [comment]
I just faced this problem. I don't think its a bug, but a confusion created by installation instructions. In the readme, the text instructs to import PdfVIewerModule in app.module.ts file, but that is just because the sample code is showing the pdf IN the app's main page (app.component.ts).... if you then try to use the pdf-viewer tag in any other page, then you get this error, until you realize that you have to import PdfViewerModule in your page's module file, not in app.module.ts.
