### ISSUE TITLE
[(page)]="pageVariable" not working

### ISSUE THREAD

**Issue by frontr-uk** [VadimDez/ng2-pdf-viewer#521]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

**Comment by seopei** [comment]
Hi, What exactly does not work for you?

**Comment by s5m4** [comment]
I came to look for a solution for the same issue. 

The ng2-pdf-viewer component generally works great in my project, however, there are issues passing in the page number when the PDF is reloaded. I use the component to build a PDF-preview-section where the PDF needs to refresh quite a lot since it is generated from user input. The PDF gets rendered on the server when the user hits a "refresh preview"-button and is passed to the component as a Unit8Array. When the user is on page 2 of the currently rendered PDF and then hits the refresh button she should get the newly created PDF displayed on page 2 - BUT after a refresh it always displays on page 1. I have **[show-all]=false** (as I read that [(page)] definitely doesn't work with [show-all]=true at the moment.)

I'm using Angular 8 and everything so far is working fine. Also, the (pageChange) event fires with the correct page number (and displays correctly in the console).

`<div class="pdf-body">
        <pdf-viewer
            [src]="pdfPreviewSource"
            [(page)]="currentPreviewPage" 
            [original-size]="originalSize"
            [zoom]="zoom" 
            [show-all]="showAll"
            [stick-to-page]="stickToPage" 
            [render-text]="renderText" //false
            [external-link-target]="'blank'"
            (error)="onPdfViewerError($event)"
            (pageChange)="onPageChange($event)"
            (after-load-complete)="afterLoadComplete($event)"
        ></pdf-viewer>`

I read in another issue that a possible solution to this problem would be to use [page] (<- so only input here) and extract the current page from the (pageChange) event. However, I could not come up with a clean solution for that since the event is fired while loading the PDF with a page number of 1. 

Another thought was to cache the page number when the user hits refresh, load new PDF and set page number on the (after-load-complete) event. This doesn't work because the event seems to get fired before the PDF is really finished loading -> and I end up on page 1 again whatever the number I put in is. 

Here is a nasty workaround using a timeout function in a method triggered on (after-load-complete), only showing the relating methods: 

`export class PreviewComponent {
  
  // variables for PDF-previewer
  pdfPreviewSource: ArrayBuffer;
  currentPreviewPage = 1;
  previousPreviewPage = 1;
  originalSize = true;
  zoom = 1.0;
  showAll = false;
  stickToPage = false;
  renderText = false;
  autoresize = false;
  outline: any[];
  error: any;

  constructor(private cdRef: ChangeDetectorRef) { }    

  private handlePreviewWindow() {
    if(this.windowAlreadyOpen === false) {
     
	  this.currentPreviewPage = 1; 
      this.updatePDFPreviewData();
      this.openPreview();
    } else {
	
      this.previousPreviewPage = this.currentPreviewPage;
      this.currentPreviewPage = 1;
      this.updatePDFPreviewData();
	  
    }
  }
  
  private updatePDFPreviewData() {
    this.webService(xxx).subscribe(response => {
      this.pdfPreviewSource = this.base64ToArrayBuffer(response.pdfcontent);
    });
  }
  
  afterLoadComplete(event: any) {
    setTimeout( () => { 
      this.currentPreviewPage = this.previousPreviewPage; 
      this.cdRef.detectChanges();
    }, 100);
  }
}`

Is there something I'm doing wrong here so that the ng2-pdf-viewer behaves like this? Do you have any thoughts on how to accomplish this better? Is it a bug? 

Kind regarsds and thanks for any thoughts!
