### ISSUE TITLE
E-Signature not displaying

### ISSUE THREAD

**Issue by mindofai** [VadimDez/ng2-pdf-viewer#602]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

I was able to display the PDF successfully but the e-signature from OneSpan is missing. I tried downloading the raw pdf file and it shows when opened, 

![image](https://user-images.githubusercontent.com/18261468/80281429-bc4ae080-873d-11ea-995f-b56a8ab8f8ff.png)

but when being displayed thru ng2-pdf-viewer, it doesn't show.  I tried out the fix from #335, but it didn't work for me. 

Here's the sample PDF:
[mycomplaintform.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/4533042/mycomplaintform.pdf)

Thanks!

**Comment by LAlves91** [comment]
Hi @mindofai !

This problem is actually related to PDFjs, Mozilla's library for PDF rendering, which ng2-pdf-viewer relies on. According to PDFjs's issue [1076](https://github.com/mozilla/pdf.js/issues/1076), the signature will remain hidden until the library has a signature verification feature working.

There's a "fix" which can be used in order to make the signature visible: serve your own pdf.worker.js to ng2-pdf-viewer, changing it in order to make the Sig field visible:

```
diff --git a/src/assets/pdf.worker.js b/src/assets/pdf.worker.js
index 5049e9eec..10d19f50c 100644
--- a/src/assets/pdf.worker.js
+++ b/src/assets/pdf.worker.js
@@ -28213,8 +28213,9 @@ function () {
             case 'Ch':
               return new ChoiceWidgetAnnotation(parameters);
           }
-
-          (0, _util.warn)('Unimplemented widget field type "' + fieldType + '", ' + 'falling back to base field type.');
+          if (fieldType !== 'Sig') {
+            (0, _util.warn)('Unimplemented widget field type "' + fieldType + '", ' + 'falling back to base field type.');
+          }
           return new WidgetAnnotation(parameters);
 
         case 'Popup':
@@ -28684,7 +28685,7 @@ function (_Annotation) {
     if (data.fieldType === 'Sig') {
       data.fieldValue = null;
 
-      _this2.setFlags(_util.AnnotationFlag.HIDDEN);
+      // _this2.setFlags(_util.AnnotationFlag.HIDDEN);
     }
 
     return _this2;
```

The problem is: you'll have to fix ng2-pdf-viewer's and pdfjs's versions, because any change could cause conflict between PDFjs's version of the worker and yours, generating unexpected results or even break PDF rendering.

**Comment by rmhrisk** [comment]
You can view and verify PDF digital signatures with this https://verify.ink/

**Comment by simianstyle** [comment]
@LAlves91  Commenting out that line or even the entire if statement still does not allow rendering of the signature as per the example pdf provided by @mindofai
