### ISSUE TITLE
 Invalid 'reference' directive syntax.

### ISSUE THREAD

**Issue by zhangDlufei** [VadimDez/ng2-pdf-viewer#617]
run "ng serve"ERROR ————

ERROR in node_modules/@types/pdfjs-dist/index.d.ts(7,1): error TS1084: Invalid 'reference' directive syntax.

and  Browser console ERROR ————

“pdf.js:7221 Uncaught (in promise) TypeError: Promise.allSettled is not a function
    at MessageHandler._deleteStreamController (pdf.js:7221)
    at MessageHandler._processStreamMessage (pdf.js:7160)
    at Worker.MessageHandler._onComObjOnMessage (pdf.js:6817)
    at ”

Does anyone have this problem？please

**Comment by werts** [comment]
解决了吗？

**Comment by zhangDlufei** [comment]
> 解决了吗？

还没有解决（去看上一楼的问题，有人说解决了类似的，但需要升级版本

**Comment by werts** [comment]
看起来是typescript的问题，我这边版本为2.7.3  已经放弃了，使用 默认的embed

**Comment by zhangDlufei** [comment]
> 看起来是typescript的问题，我这边版本为2.7.3 已经放弃了，使用 默认的embed

我也改成了用embed，但是想把下载按钮禁用掉，你有方法吗？

**Comment by aanchal-adk** [comment]
@zhangDlufei I'm getting the same error. The error appears in the console in example app as well:https://stackblitz.com/edit/ng2-pdf-viewer.

**Comment by VadimDez** [comment]
@aanchal-adk I don't see any errors in the console:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/3748453/94067480-34512b80-fdee-11ea-9581-fc7042d5c8f3.png">

**Comment by aanchal-adk** [comment]
@VadimDez That's weird because I still get the error in the console.
![Screenshot from 2020-09-30 16-09-23](https://user-images.githubusercontent.com/22411120/94674212-90a8d380-0337-11eb-80f9-bc03b20b3f62.png)
 But changing the zone.js version to 0.10.3 worked for me like someone shared in this issue: https://github.com/VadimDez/ng2-pdf-viewer/issues/616#issuecomment-644090943
