### ISSUE TITLE
ng2-pdf-viewer is not working on bootstrap modal

### ISSUE THREAD

**Issue by Sachinbekre** [VadimDez/ng2-pdf-viewer#645]
<pdf-viewer 
          [src]="pdfUrl"
          [rotation]="0"
          [fit-to-page]="true"
          [original-size]="true"
          [show-all]="true"
          (after-load-complete)="afterLoadComplete($event)"
          (page-rendered)="pageRendered($event)"
          (on-progress)="showGif($event)" style="display: block;"
        ></pdf-viewer>

**Comment by abdulbarik** [comment]
Hi team,
I am facing same issue, is there any update on it?

**Comment by abdulbarik** [comment]
@Sachinbekre  I was checking the event and I think the pdf gets rendered before your modal.
just make some delay to set your `pdfURL` value and it'll work.
Its not feasible solution to use `setTimeout` here but to make it work you can use.

Just an example here

`      getFullImage(item: any) {
          setTimeout(()=>{
             this.targetImageURL = item.doc.signedURL;
         },2000);
     }
`

**Comment by VadimDez** [comment]
I can't reproduce the error, here I made an example with a bootstrap modal and put a pdf in it, works fine
https://stackblitz.com/edit/ng2-pdf-viewer-bootstrap-modal?file=src%2Fapp%2Fapp.component.html

**Comment by elize-vockerodt** [comment]
I came across tis page because I'm also having issues with Bootstrap modal and the PDF's not rendering correctly. Mostly the pages in view (that you see before having to scroll down, and maybe 1 more) render, the rest stays blank after scrolling down. I tested it with the viewer code outside and inside the modal, outside works. If i render the PDF's width to like 50px wide (very small) so that i dont trigger any scrollbar, then they all render again. 

9 page PDF at 400px (half of the pages dont render when i scroll down)
![Screenshot 2023-03-27 at 15 20 31](https://user-images.githubusercontent.com/54170626/227949342-e1bc9a7c-2266-4bd6-a64c-5764ef04ea9b.png)

Same PDF at 50 px in width without a scrollbar - all render. 
![Screenshot 2023-03-27 at 15 20 51](https://user-images.githubusercontent.com/54170626/227949372-4338df32-9bca-4388-a0b5-66a6ff9d6901.png)

This is a very annoying issue. So far I havent figured out a trick to solve it.

**Comment by helen-andronova** [comment]
> I can't reproduce the error, here I made an example with a bootstrap modal and put a pdf in it, works fine https://stackblitz.com/edit/ng2-pdf-viewer-bootstrap-modal?file=src%2Fapp%2Fapp.component.html

You use content in your example. Viewer does not work in modal with Component
