### ISSUE TITLE
Highlighting doesn't match text size

### ISSUE THREAD

**Issue by marabu-edv** [VadimDez/ng2-pdf-viewer#680]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
When searching for words within the PDF, the highlighting doesn't always match the rendered text. Especially for words within headlines the highlighting is too small and covers only the left buttom corner of the word. 
When manually selecting text of the textlayer the font size matches the rendered PDF text, but for words highlighted by searching, the font size of the matching word gets scalled down in the textlayer causing the highlighting to not match the rendered PDF text.

(green is the highlighting through the search for "Time"
blue by manually selecting, to see the white textlayer)
![highlighting](https://user-images.githubusercontent.com/52482998/98170535-75a92080-1eee-11eb-8de3-780453509eb2.jpg)

**Comment by priyankabasu123** [comment]
I am facing the same issue when searching in the PDF, using browser search. The matched texts that are highlighted appear blurred and are overlapping with a slightly transparent text layer that does not sit perfectly behind. Would appreciate if we can get a solution or work around. 
Version : 6.3.2
Browser : Chrome and Firefox

<img width="88" alt="Screen Shot 2020-12-09 at 5 20 57 PM" src="https://user-images.githubusercontent.com/7137214/101956785-3032ee00-3c26-11eb-8ef0-6206116ebc7b.png">

<img width="97" alt="Screen Shot 2020-12-09 at 5 21 10 PM" src="https://user-images.githubusercontent.com/7137214/101956808-39bc5600-3c26-11eb-8590-1406aa12eefc.png">

**Comment by stephanrauh** [comment]
That's a problem the library inherits from pdf.js. The PDF file itself is rendered as an image. To enable text selection, there's a text layer above the image. That's a div containing the text as, well, text, using a font that matches the font of the PDF file as good as possible. However, the algorithm contains a lot of heuristics and has to cope with a wide variety of font. As a result, the text layer is only an approximation. Usually it's a couple of pixels off. If you want to solve the problem, open a bug ticket at Mozilla's project.

@priyankabasu123 The shadow text is caused by your CSS. Maybe the CSS code of your application interferes with the CSS code of pdf.js.

**Comment by marabu-edv** [comment]
I understand, that there are going to be little differences, but that doesn't explain why the approximated text matches the rendered text at first and then suddenly changes the text to some kind of default, when searching for a string. 
I will however open a ticket at Mozilla now, as you suggested

**Comment by stephanrauh** [comment]
@timvandermeij I've sent @marabu-edv to you.

@marabu-edv Now that you say it - I've never seen the "jumping marked text" problem. Can you send us a reproducer? Maybe even a short video?

**Comment by stephanrauh** [comment]
@marabu-edv I've found an error description that reminds me of your error description. If that's correct, the bug is solved with pdf.js 2.7. Unfortunately, I'm afraid ng2-pdf-viewer won't support pdf.js 2.7 soon. ng2-pdf-viewer uses the versions that have been officially called "stable". So I suspect the next version of ng2-pdf-viewer will use pdf.js 2.5.
