### ISSUE TITLE
Can't build for IE 11 any more

### ISSUE THREAD

**Issue by george-oiko** [VadimDez/ng2-pdf-viewer#747]
I'm using the workaround with versions:

"ng2-pdf-viewer": "6.2.0"
"pdfjs-dist": "2.3.200"
"@types/pdfjs-dist": "2.1.3"
as recommended by members in previous issues for IE 11 es5 to work.

But suddenly i started receiving the following:

ERROR in node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:100 - error TS2305: Module '"F:/AZagent/UFE/_work/9/s/UFE-DEV/Angular/node_modules/ng2-pdf-viewer/node_modules/@types/pdfjs-dist"' has no exported member 'PDFPromise'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';

How is this possible? I'm fetching specific versions.

**Comment by almothafar** [comment]
It is a build issue, what IE has to do with it?
install 6.4.1 that issue is fixed already.

Also, remove 
```
"pdfjs-dist": "2.3.200"
"@types/pdfjs-dist": "2.1.3"
```

From your package.json

Side note: IE 11 is dead.

**Comment by meraj-ahmed** [comment]
> Side note: IE 11 is dead.

@almothafar not technically true. IE 11 is part of Windows 10, so it continues to receive security patches. Although Microsoft and many others are discontinuing support for it with their own applications, there are still some customers that rely on it for legacy reasons. They are an increasingly minuscule percentage, but some developers have to continue to support it for specific clients.

**Comment by almothafar** [comment]
@meraj-ahmed IE is barely 1% of the browser's market share (0.94% to be exact), providing internet explorer with Windows 10 does not mean it will be still alive! for example, Microsoft 365 will end IE 11 support in August this year! also, this issue is NOT related to IE, it is a build issue, es6 IS supported in IE 11 https://caniuse.com/?search=es6 

If he wants to support the old man, he needs to use an older version of everything.

And since it is for Angular you can use polyfills from angular to support IE 11 https://angular.io/guide/browser-support 

So, IE 11 is dead, and if it is still alive, we have to kill it, it MUST die.

**Comment by meraj-ahmed** [comment]
@almothafar I agree with you. I'm just saying that there are some cases where not everyone is able to completely drop support for business reasons.
